messages:
  enable: "&a插件已开启"
  disable: "&c插件已关闭"
  shout-format: "&6[喊话]&e[%server%(%players%)]&b[%player%]&8:&f%message%"
  invite-format: "&e[点击传送]"
  format: "&b&l✈ &7 %player% &b&l邀请你加入 &e%server% &b&l房间！并说：%message%\n&6&l点击此信息 &b&l加入！"
  hover-format: "&a点击传送至服务器 &6%server%"
  run-in-console: "&c该命令不能在控制台执行！"
  in-cooldown: "&c你还需等待 &b&l %timeleft% &c秒才能使用此指令！"
  in-blocked-server: "&c你不能在该服务器执行此命令！"
  invitation-expired: "&c该邀请已过期"
  block-invite-message: "&e已屏蔽所有喊话消息"
  unblock-invite-message: "&a已解除屏蔽，你现在可以收到新的喊话消息了"
  reload-plugin: "&a插件配置重载成功"

blockedServers:
  - "登录服"
  - "login"

canBlockedServerSeeMessages: false

servers:
  lobby: "&a大厅"
  bedwars: "&e起床战争"

times:
  cooldown: 30
  expiry: 100

mysql:
  host: 'localhost'
  port: '3306'
  database: 'minecraft'
  username: ''
  password: ''
  useSSL: false